### ISSUE TITLE
the program cant remove the drm 

### ISSUE THREAD

**Issue by Jackmatim** [13xforever/DeDRM#4]
Removing DRM...
5ea0bebb-e7cb-4dd3-8513-763fb6beb367    EPub      Kobo      Fail      5ea0bebb-e7cb-4dd3-8513-763fb6beb367
        Error: Value cannot be null. (Parameter 'path1')
Done.

**Comment by 13xforever** [comment]
Duplicate of #1.

You'll have to debug it yourself, there's no support for end users.
